### ISSUE TITLE
DEV: INV limit 0 at startup till capacity determined

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#159]
I observed on the dev branch that at startup the INV limit is set to 0 until the capactiy of the inverter is determined. This is risky as the INV might get stalled and requires a restart. 

Ideally the INV at startup the minimum value should be taken (10W) and set for all channels i.e. 40W to ensure that the INV does not get stalled till the capacity is determined.

I have attached the corresponding log.
[solarFlow-startupIssue.log](https://github.com/reinhard-brandstaedter/solarflow-control/files/14622798/solarFlow-startupIssue.log)

**Comment by reinhard-brandstaedter** [comment]
Confirmed this can happen. Fix should be easy.

**Comment by tuxianerDE** [comment]
issue resolved
