### ISSUE TITLE
INV: Did not increase direct panels though solar radition increased drastically.

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#164]
I observed that today afternoon the sun - finally - came out behind the cloud. The inverter in this case did not increase the limit to better match the new direct irridation.

I manually entered in openDTU the limit of 100%, which directly increased the output of the INV accordingly. Afterwards the script properly picked the new limit out and steered it - supposedly correctly.

I have attached a graph showing that it is was not due to any interval limitation as the increased power was present long enough to get detected. Further I attached a screenshot from my DTU showing that the limit was maxed out by the output and yet the script did not trigger any acction up until I manually intervened.

![SolarPaneloOutput](https://github.com/reinhard-brandstaedter/solarflow-control/assets/47778296/336742cf-37de-47f3-874f-7a948b568e8d)
[solarflow-control-directpanel_increase.log](https://github.com/reinhard-brandstaedter/solarflow-control/files/14627940/solarflow-control-directpanel_increase.log)

**Comment by tuxianerDE** [comment]
![Screenshot_20240317-161835_Chrome](https://github.com/reinhard-brandstaedter/solarflow-control/assets/47778296/df85ccb3-5cd9-4ed7-b7f2-51665f6bbe30)

**Comment by tuxianerDE** [comment]
After manually changing the limit to 100%
![Screenshot_20240317-161918_Chrome](https://github.com/reinhard-brandstaedter/solarflow-control/assets/47778296/7d9f963d-6fe8-4397-bac7-6af64fb286dc)

**Comment by tuxianerDE** [comment]
Is it possible that the diff limit of 30W is too large and hence the INV did not trigger?

**Comment by reinhard-brandstaedter** [comment]
That was my thought too....

**Comment by tuxianerDE** [comment]
Issue resolved. Given the limit function & fixed interval in case no triggered received as a health check
