### ISSUE TITLE
BUG: when limiting SF via inverter only it can happen that the limit/output is fluctuating

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [reinhard-brandstaedter/solarflow-control#165]
This scenario happened today when there was constant load in the house during late sunset. The limiting started to fluctuate heavily between invverter and solarflow limit. Resulting in a rather harmonic swing.

<img width="1582" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-control/assets/10830223/ad3a98b1-89af-479c-99c0-6c674991f4e6">

Upon investigation I suspect that this has to do with the very low (but still positive DC values of direct panels). Once the DTU reported absolute 0 for DC panels this went back to normal by itself.

**Comment by tuxianerDE** [comment]
Adding the current state from 20MAR24 test.
![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/47778296/8e72a660-3d9d-4942-a67c-f6142ae5649a)
[solarFlow.zip](https://github.com/reinhard-brandstaedter/solarflow-control/files/14664964/solarFlow.zip)

**Comment by tuxianerDE** [comment]
Update provided from 26.03.2024
In the morning when the offset kicked it and first input came from the direct panels I observed the behaviour again. Given that I require a long offset time in the morning it goes on for some time.

![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/47778296/f467864d-81d5-48e1-9c4c-81a704119bc1)
[solarFlow-26MAR24-zickZack.zip](https://github.com/reinhard-brandstaedter/solarflow-control/files/14758189/solarFlow-26MAR24-zickZack.zip)
