### ISSUE TITLE
fully charged timeframe

### ISSUE THREAD

**Issue by AzraelsDisk** [reinhard-brandstaedter/solarflow-control#174]
Hi Guys,

is it possible to set the 32hrs someware as a variable? maybe i missed it, sorry

Regards,
Azra

2024-03-19 09:37:14,884:INFO: Battery hasn't fully charged for 41.0 hours! To ensure it is fully **charged at least every 32hrs** not discharging now!

**Comment by reinhard-brandstaedter** [comment]
Yes, by changing [this](https://github.com/reinhard-brandstaedter/solarflow-control/blob/e864140b374823bf843026850fc8ba46c08d1bc6/src/config.ini#L21) config setting.

**Comment by AzraelsDisk** [comment]
Sorry for being blind….Am 19.03.2024 um 11:09 schrieb Reinhard Weber (Brandstaedter) ***@***.***>:﻿
Yes, by changing this config setting.
