### ISSUE TITLE
Dev : Hub limit setting gets dropped due to too early interval

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#197]
Obsereved that during offset the hub limit got set to 0 after drop whilst the grid usage was in the positive so in theory battery could have been used.

Hub does not return with a limit >0; in the logs I obsered that a limit was set to 800, however since the last command was not too long ago enough it got dropped. Problem was though that no further limit function got triggered until a bigger light got switched on. This might work (more or less well) when a person is at home but in absence this might proof inefficient.

![hub-missingLimit](https://github.com/reinhard-brandstaedter/solarflow-control/assets/47778296/6d177649-e56e-4d1a-9899-f79ba31c3de0)

[solarFlow-limitMissed.log](https://github.com/reinhard-brandstaedter/solarflow-control/files/14898368/solarFlow-limitMissed.log)

**Comment by reinhard-brandstaedter** [comment]
This should be fixed by triggering the limitFunction now every 120s as a backup to no changes in demand (or very slow changes that do not trigger via difference detection). Additionally the Hub rate-limit has been improved to only count if the (new) limit has been applied.
