### ISSUE TITLE
Shelly Pro 3EM not working

### ISSUE THREAD

**Issue by ShadowJumper** [reinhard-brandstaedter/solarflow-control#237]
Im testing solar flow control with a shelly pro 3em, but this does not working as expectet.

Problem is that sfc want to subscribing "emeter/0/power", "emeter/1/power" and "emeter/2/power", but this are not existing on pro 3 em mqtt topics.

The only data that exists are "..../status/em:0" and "..../status/emdata:0".

So sfc cant get the current power.

**Comment by reinhard-brandstaedter** [comment]
See [here](https://github.com/reinhard-brandstaedter/solarflow-control/issues/138)
