### ISSUE TITLE
On latest dev build issue with format code "W"

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#246]
May 13 19:12:23 babylon solarFlowDev[15841]: Exception in thread Thread-137:
May 13 19:12:23 babylon solarFlowDev[15841]: Traceback (most recent call last):
May 13 19:12:23 babylon solarFlowDev[15841]:   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
May 13 19:12:23 babylon solarFlowDev[15841]:     self.run()
May 13 19:12:23 babylon solarFlowDev[15841]:   File "/usr/local/lib/python3.11/threading.py", line 1401, in run
May 13 19:12:23 babylon solarFlowDev[15841]:     self.function(*self.args, **self.kwargs)
May 13 19:12:23 babylon solarFlowDev[15841]:   File "/solarflow/utils.py", line 29, in _run
May 13 19:12:23 babylon solarFlowDev[15841]:     self.function(*self.args, **self.kwargs)
May 13 19:12:23 babylon solarFlowDev[15841]:   File "/solarflow/solarflow-control.py", line 415, in deviceInfo
May 13 19:12:23 babylon solarFlowDev[15841]:     limitHomeInput(client)
May 13 19:12:23 babylon solarFlowDev[15841]:   File "/solarflow/solarflow-control.py", line 354, in limitHomeInput
May 13 19:12:23 babylon solarFlowDev[15841]:     inv_limit = inv.setLimit(limit)
May 13 19:12:23 babylon solarFlowDev[15841]:                 ^^^^^^^^^^^^^^^^^^^
May 13 19:12:23 babylon solarFlowDev[15841]:   File "/solarflow/dtus.py", line 236, in setLimit
May 13 19:12:23 babylon solarFlowDev[15841]:     log.info(f'Current inverter AC output ({self.getCurrentACPower():.0W}) is within acceptable overage ({self.acLimit:.0}W +/- 20W), keeping limit at {inv_limit:.0}W')
May 13 19:12:23 babylon solarFlowDev[15841]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 13 19:12:23 babylon solarFlowDev[15841]: ValueError: Unknown format code 'W' for object of type 'float'

**Comment by reinhard-brandstaedter** [comment]
cp error fixed
