### ISSUE TITLE
Bypass switch not available in HA anymore

### ISSUE THREAD

**Issue by mavo** [reinhard-brandstaedter/solarflow-control#254]
Hellow @reinhard-brandstaedter (and maybe @ricariel as I think you did the most for the HA integrations),

for some reason, since 3 days (shown by HA in the entity state) the switch for BP mode is not available anymore.
![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/13994768/1d4bb754-3e82-48d8-b331-79524b928355)

This used to work fine, and I was able to flip it which also worked, but now its gone. I did not update the app (until yesterday, in a desperate attempt of fixing it by updating the app). Do you have any idea what could be the cause of this?
Only thing I know that happened was a firmware update of the NAS where I run the containers. But as everything else works, I do not really consider this as the direct cause.

What kind of data / logs can I provide to investigate this?

Thanks in advance,
MaVo

**Comment by reinhard-brandstaedter** [comment]
You should have “Bypass Mode” and “Bypass State” available, can you check?

<img width="414" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-control/assets/10830223/7062de63-4ca6-4fac-8407-25f5db4e230b">

**Comment by mavo** [comment]
Ahhh, I have no Idea why I did not see this, but yeah. You're right, that exists.

The only downside of it, its not populated with its current state -> it shows an empty selection (like in your screenshot).
The older version did indicate its current value and updated it when the value changed in MQTT.

**Comment by reinhard-brandstaedter** [comment]
I actually just fixed a bug in the HA template for that selector. It should now be properly updated  and propagated!

**Comment by mavo** [comment]
Awesome, I'll give it a try and close when it works, thank you!

**Comment by mavo** [comment]
Hello @reinhard-brandstaedter,

I now pulled latest dev build and I can see in the container, that the template is updated. However, HA still shows
<img width="200" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-control/assets/13994768/40eca2c4-b44d-4076-96b7-54bbf7dd8f3e">
Anything I can do?

MaVo

**Comment by mavo** [comment]
Any update, anything I can?

**Comment by reinhard-brandstaedter** [comment]
I added the passMode to sensors now to get the current state.
The select switch is not updating but works for changing/setting the passMode

<img width="335" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-control/assets/10830223/04024381-ba89-41a7-b6f6-3739c10aa292">

**Comment by mavo** [comment]
Thank you. I can see the new entity in HA 🙇
