### ISSUE TITLE
Question regarding hoymiles inverter

### ISSUE THREAD

**Issue by mavo** [reinhard-brandstaedter/solarflow-control#267]
Hello,

this is NOT a bug report for sf-control, it works rather well lately. I just noticed a strange thing in my setup, which I cannot really explain.
The situation is as follows: When there is plenty of sun available and the demand is also high due to washing machine running for example, sf-control sets the output of the inverter to 100% (or even greater sometimes, which should not matter), but the inverter only passes around 550W of the possible ~800W. I am using an HMS-1600-4T on which I have 2 inputs used and 2 empty.
The temps of the inverter are under control, at never reaches anything above ~55°C, so I don't think this is the reason.

Did any of you has seen similar behaviour?

MaVo

**Comment by reinhard-brandstaedter** [comment]
A inverter "splits" the limit to the number of inputs. The limit is not calculated on the AC side (house output).
In your case a 1600W max limit across 4 channels means 4x400W input. If you only have 2 inputs used the maximum you will get is 800W 2x400W input.

sf-control takes this into account when individual input channels are not producing and others are producing.
Imagine you have only 2 panels (2 inputs) producing 200W each and want 400W on the output. In this case the inverter limit must be set to 800W to get 400W, becasue 800W/4 (input channels) = 200W per channel.

This is why sf-control is optimized for direct panels input and hub input.

**Comment by mavo** [comment]
I think I did not explain my issue clear enough. I am aware that my 4 port inverter only can deliver 400W per channel. Thats alright. I am also aware that I have only 2 ports connected, making it 800W max output of the inverter for me, which is absolutely correct. I do not expect more.

However, what I mean is, sf-control sets the inverter to 100% (1600W * 50% (of used ports) = 800W) but in this situation, the inverter only emits 550W, which is the weird part.

**Comment by reinhard-brandstaedter** [comment]
I assume the hub output limit is not set? What is the max inverse power set to on the hub? Likely you are using y-cables to connect the two channels? This can cause a "race" between the MPTT trackers of the hoymiles as there is no galvanic separation of the MPTTs (connected via y-cable). If you can get a V/A diagram of your inverter data you likely see a lot of fluctuation for both channels on voltage and current.

**Comment by mavo** [comment]
>I assume the hub output limit is not set?

I have the hub output limit set to 800W as well.

> If you can get a V/A diagram of your inverter data you likely see a lot of fluctuation for both channels on voltage and current.

No idea how to do this 🙈 

> Likely you are using y-cables to connect the two channels?

Yes, I am using a Y-splitter. However, it usually works to get around 800W from the inverter.
I now checked the output and the temps, and it actually never went higher then 550W when the inverter crossed a threshold of 50°C 🤔 

![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/13994768/8525ed26-ff30-4fea-8ab3-af5a798cf222)

**Comment by reinhard-brandstaedter** [comment]
Your DTU reports Voltage (V) and current (A) for every input channel, thouse you should be able to chart.

If it correlates with temperature however that could also be a reason. Try to cool down the inverter.

**Comment by mavo** [comment]
Well... How to cool it?
The inverter is inside the attic, do you mean blowing with a fan onto it would help? It probably only moves some warm air around in the attic, not much more, wouldn't it?

I anyway will give it a go. Found an older smart-plug which I can use to control when the fan should move some warm air around. Maybe that's enough, and if not there is not much more I can actually do ^^

**Comment by reinhard-brandstaedter** [comment]
50C isn’t actually too hot. Mine sometimes goes up to 50 as well (also in the Attic). But my old HM600 directly under the roof in the past also started limiting but that was at 60-65C….

Anyways maybe reach out to hoymiles. Not much to do here…

**Comment by mavo** [comment]
True, will close the ticket.
Thanks as always, keep up the great work!

**Comment by mavo** [comment]
Btw, I added a fan and a smart plug to control when it should run.

First I only pointed it to the inverter only, but this did not help too much and I still saw some throttling.

When I changed it so that it also was pointing to the hub it got better and since then I had no throttling anymore 🤷‍♂️
