### ISSUE TITLE
Dev: Possible config values via MQTT ignore config.ini at startup

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#281]
hey,

I pulled the latest dev build with the amazing option to set more values on the via i.e. via HomeAssistant.

However I noticed that at startup values like sunrise and sunset offset are actually set to default values. An idea: if the server starts up the config.ini values are taken into consideration. Given that the new "day discharge" variable is persistent the logic would not be touched.

**Comment by reinhard-brandstaedter** [comment]
Breaking change: I moved the config settings for offset from [global] to the [control] section!

**Comment by tuxianerDE** [comment]
Issue closed.  variables need to move to new section
