### ISSUE TITLE
Dev: Day Discharge Variable persistent on MQTT

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#282]
Thanks for the new day discharge variable in my consideration really useful for quiet some use cases. 

A question however, would it make senes to remove the retained message of day discharge at midnight (or so) otherwise the variable would need to be actively switched back upon return (vacation scenarion). Whilst it might make sense that it is determined everyday what to do with this switch based on presence or SoC or or.

Resetting the variable at midnight would elimate at least the risk of a "sticky" MQTT message that interferes.

@canbaytok @reinhard-brandstaedter  what are you thoughts?

**Comment by canbaytok** [comment]
I have to admit, that I'm not a huge fan of removing the retained message at midnight as it defeats the whole purpose of publishing a retained message in the first place. 

solarflow-control provides a simple interface to set the control parameters via MQTT/Home Assistant, which is pretty much all you'll need to program more complex logic for setting bypass, daytime discharge, charge through, etc. via Home Assistant Automations/Scripts.

You could create a "Vacation" helper toggle in Home Assistant and tie the toggling to a scipt, which enables/disables the necessary switches of solarflow-control, thus completly changing the behavior of the system, with the push of a button.
