### ISSUE TITLE
Peaks up and Down since last dev update

### ISSUE THREAD

**Issue by AzraelsDisk** [reinhard-brandstaedter/solarflow-control#295]
![image](https://github.com/user-attachments/assets/c2791ed8-3ac1-402e-8c1c-d3acc93c5857)
between 11:50 and 12:04 I had stoppe the script and restartet after...

**Comment by AzraelsDisk** [comment]
it looks like the demand calcculation is wrong?

**Comment by tuxianerDE** [comment]
Could you observe the behaviour again with the latest build? and attach an updated log? If you could not propose to close, can still open it when it happens again.

**Comment by AzraelsDisk** [comment]
dev or stable?

**Comment by AzraelsDisk** [comment]
> @AzraelsDisk dev

Stack updated, test is running... but *sun* is missing...
