### ISSUE TITLE
Dev: CT Mode detected MinSoC not adjusted

### ISSUE THREAD

**Issue by tuxianerDE** [reinhard-brandstaedter/solarflow-control#312]
Hey just pulled the latest dev build.

I noticed that the system detects correctly that we are in CT mode and set it accordingly, it also states that the MinSoC needs to be adjusted to go all the way from 100 to 0. But the actual MinSoC is not getting set to 0% according to the log and also on MQTT the value is still the configured value of 1%.

> 2024-11-21 11:37:20,277:INFO: We can control SoC levels but the SoC boundaries read from hub are not available yet. Waiting for update to re-check conditions
> 2024-11-21 11:37:20,277:INFO: Reading last full time: 2024-11-05 16:09:11
> 2024-11-21 11:37:28,914:INFO: Received charge-through control: True, Control SoC: True, SocMax: 100.0%, SocMin: 1.0%
> 2024-11-21 11:37:28,914:INFO: To turn on charge-through with a full-cycle we need to adjust the min SoC from 1.0% to 0%!
> 2024-11-21 11:37:28,914:INFO: Setting minimum charge level to 0%
> 2024-11-21 11:37:28,914:INFO: Set ChargeThrough: False => True
> 2024-11-21 11:37:28,914:INFO: Updating charge through stage: idle => charging
> 2024-11-21 11:37:28,914:INFO: Setting maximum charge level to 100%
> 2024-11-21 11:37:28,915:INFO: Setting minimum charge level to 1%
> 2024-11-21 11:37:28,915:INFO: Received charge-through control: ON, Control SoC: True, SocMax: 100.0%, SocMin: 1.0%`

**Comment by reinhard-brandstaedter** [comment]
You are in the "upwards" (charging) state of the charge through phase.
Once you reach 100% you will go into the "downwards" (discharging) phase and the lower limit should be adjusted accordingly to 0.
Can you observe this once 100 has been reached?

**Comment by tuxianerDE** [comment]
> You are in the "upwards" (charging) state of the charge through phase. Once you reach 100% you will go into the "downwards" (discharging) phase and the lower limit should be adjusted accordingly to 0. Can you observe this once 100 has been reached?

Hey,
jep will monitor, 100% should be reached based on current progress around mid January 2025 :D
