### ISSUE TITLE
Topic House is not used anymore after last update

### ISSUE THREAD

**Issue by AzraelsDisk** [reinhard-brandstaedter/solarflow-control#64]
![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/117444481/b387acf5-7d7c-406e-a9ff-a12e7068d6d6)
![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/117444481/5302eb56-3d49-464e-aa18-03755c3e5994)
![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/117444481/b603d054-0b22-4db5-b0ad-42075138732f)

**Comment by AzraelsDisk** [comment]
It looks like some of the variables are ignored, is there an other way no to set them?

**Comment by reinhard-brandstaedter** [comment]
There is now a new (additional) way to provide configuration via a ```config.ini``` file in the program directory. Maybe I've introduced a bug here.
Please try providing a config.ini (template found in the src dir)

**Comment by AzraelsDisk** [comment]
How could this be done via Synology container manager? There is could only add variables. ThxAm 07.10.2023 um 20:31 schrieb Reinhard Weber (Brandstaedter) ***@***.***>:﻿
There is now a new (additional) way to provide configuration via a config.ini file in the program directory. Maybe I've introduced a bug here.
Please try providing a config.ini (template found in the src dir)

**Comment by reinhard-brandstaedter** [comment]
It's the same as with other docker runtimes, you can mount a single file as a "volume" into a single file into the container as well: https://docs.docker.com/storage/volumes/

But there is indeed a problem when there is no config file present, default values are applied.... needs a fix
