### ISSUE TITLE
Safe last state on restart

### ISSUE THREAD

**Issue by ricariel** [reinhard-brandstaedter/solarflow-control#95]
Every time the container restarts (automatically if new image is present on docker hub) important values are lost.
Example:
solarflow.py -> 
self.lastFullTS
self.lastEmptyTS

Would be nice if these and perhaps other values get stored somewhere.

**Comment by reinhard-brandstaedter** [comment]
Actually exactly these values are stored as retained messages in MQTT:

<img width="288" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-control/assets/10830223/cc2c3b6d-52bc-4298-9f4a-51f259219411">

As those are retained messages they are read in again upon startup. However it could be that the mqtt broker is not persisting these retained messages upon restart?

**Comment by ricariel** [comment]
Read the code again. You are correct. Code just never reached that state with control running. Pardon.
